In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

plt.rcParams.update({'figure.max_open_warning': 0})
%matplotlib inline 

df = pd.read_csv('/users/Davwak/Downloads/Air_Quality.csv',
                dtype={
                    'LocationNamme': 'category',
                    'MeasurementType': 'category',
                    'MeasurementUnit': 'category',
                    'location': 'category'
                })

df['ObservationTime'] = pd.to_datetime(df['ObservationTime'], infer_datetime_format=True)

df = df[df.ThingID != 84]  # 
df = df[df.ThingID != 102] # These are busted devices reporting weird values.
df = df[df.ThingID != 90]  #

In [32]:
df.groupby('ThingID')['ObservationID'].nunique()

ThingID
66      90607
72     186065
78     186007
96     223724
108    153495
114    130551
120    224984
Name: ObservationID, dtype: int64

In [18]:
df.isnull().sum()

ObservationID       0
ObservationTime     0
ThingID             0
LocationName        0
MeasurementType     0
MeasurementValue    0
MeasurementUnit     0
location            0
dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1195433 entries, 0 to 1463758
Data columns (total 8 columns):
ObservationID       1195433 non-null int64
ObservationTime     1195433 non-null datetime64[ns]
ThingID             1195433 non-null int64
LocationName        1195433 non-null object
MeasurementType     1195433 non-null category
MeasurementValue    1195433 non-null float64
MeasurementUnit     1195433 non-null category
location            1195433 non-null category
dtypes: category(3), datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 58.1+ MB

In [34]:
table = df.pivot_table(values='MeasurementValue', index='ThingID', columns='MeasurementType', aggfunc=np.mean)

In [35]:
table

MeasurementType   Humidity  PM2.5 Particulates  Temperature
ThingID
66               60.550746            9.891129     5.767208
72               65.096568            8.208362    -0.719975
78               64.041758            8.878986    -0.848058
96               67.754282           10.434442    -0.182704
108              70.334404            9.018782    -2.200657
114              70.159341            9.807202    -3.888960
120              63.455020            8.455604     0.895021

In [14]:
df.loc[(df['ThingID'] == 102) & (df['MeasurementType'] == 'PM2.5 Particulates') & (df['MeasurementValue'] > 40)]

,ObservationID,ObservationTime,ThingID,LocationName,MeasurementType,MeasurementValue,MeasurementUnit,location
14294,12140,2017-08-31 22:25:03,102,Tyndall,PM2.5 Particulates,47.0,ug/m3,"(49.936131, -97.215121)"
14318,12164,2017-08-31 22:30:05,102,Tyndall,PM2.5 Particulates,44.0,ug/m3,"(49.936131, -97.215121)"
16344,10148,2017-08-31 14:27:00,102,Tyndall,PM2.5 Particulates,57.0,ug/m3,"(49.936131, -97.215121)"
16357,1005,2017-08-30 02:38:41,102,Tyndall,PM2.5 Particulates,43.0,ug/m3,"(49.936131, -97.215121)"
16378,1026,2017-08-30 02:43:43,102,Tyndall,PM2.5 Particulates,41.0,ug/m3,"(49.936131, -97.215121)"
16399,1047,2017-08-30 02:48:44,102,Tyndall,PM2.5 Particulates,41.0,ug/m3,"(49.936131, -97.215121)"
17817,465,2017-08-30 00:07:44,102,Tyndall,PM2.5 Particulates,96.0,ug/m3,"(49.936131, -97.215121)"
17832,480,2017-08-30 00:12:45,102,Tyndall,PM2.5 Particulates,95.0,ug/m3,"(49.936131, -97.215121)"
17847,495,2017-08-30 00:17:47,102,Tyndall,PM2.5 Particulates,96.0,ug/m3,"(49.936131, -97.215121)"
17865,513,2017-08-30 00:22:49,102,Tyndall,PM2.5 Particulates,94.0,ug/m3,"(49.936131, -97.215121)"
17883,531,2017-08-30 00:27:51,102,Tyndall,PM2.5 Particulates,88.0,ug/m3,"(49.936131, -97.215121)"
17901,549,2017-08-30 00:32:53,102,Tyndall,PM2.5 Particulates,84.0,ug/m3,"(49.936131, -97.215121)"
17919,567,2017-08-30 00:37:55,102,Tyndall,PM2.5 Particulates,84.0,ug/m3,"(49.936131, -97.215121)"
17937,585,2017-08-30 00:42:56,102,Tyndall,PM2.5 Particulates,78.0,ug/m3,"(49.936131, -97.215121)"
17955,603,2017-08-30 00:47:58,102,Tyndall,PM2.5 Particulates,79.0,ug/m3,"(49.936131, -97.215121)"
17973,621,2017-08-30 00:53:00,102,Tyndall,PM2.5 Particulates,65.0,ug/m3,"(49.936131, -97.215121)"
17991,639,2017-08-30 00:58:02,102,Tyndall,PM2.5 Particulates,65.0,ug/m3,"(49.936131, -97.215121)"
18009,657,2017-08-30 01:03:04,102,Tyndall,PM2.5 Particulates,61.0,ug/m3,"(49.936131, -97.215121)"
18027,675,2017-08-30 01:08:06,102,Tyndall,PM2.5 Particulates,64.0,ug/m3,"(49.936131, -97.215121)"
18045,693,2017-08-30 01:13:08,102,Tyndall,PM2.5 Particulates,62.0,ug/m3,"(49.936131, -97.215121)"
18063,711,2017-08-30 01:18:10,102,Tyndall,PM2.5 Particulates,59.0,ug/m3,"(49.936131, -97.215121)"
18081,729,2017-08-30 01:23:12,102,Tyndall,PM2.5 Particulates,57.0,ug/m3,"(49.936131, -97.215121)"
18099,747,2017-08-30 01:28:14,102,Tyndall,PM2.5 Particulates,59.0,ug/m3,"(49.936131, -97.215121)"
18117,765,2017-08-30 01:33:16,102,Tyndall,PM2.5 Particulates,59.0,ug/m3,"(49.936131, -97.215121)"
18135,783,2017-08-30 01:38:18,102,Tyndall,PM2.5 Particulates,59.0,ug/m3,"(49.936131, -97.215121)"
18153,801,2017-08-30 01:43:20,102,Tyndall,PM2.5 Particulates,53.0,ug/m3,"(49.936131, -97.215121)"
18171,819,2017-08-30 01:48:22,102,Tyndall,PM2.5 Particulates,57.0,ug/m3,"(49.936131, -97.215121)"
18189,837,2017-08-30 01:53:24,102,Tyndall,PM2.5 Particulates,60.0,ug/m3,"(49.936131, -97.215121)"
18207,855,2017-08-30 01:58:26,102,Tyndall,PM2.5 Particulates,59.0,ug/m3,"(49.936131, -97.215121)"
18225,873,2017-08-30 02:03:28,102,Tyndall,PM2.5 Particulates,61.0,ug/m3,"(49.936131, -97.215121)"
...,...,...,...,...,...,...,...,...
32209,15878,2017-09-01 11:29:52,102,Tyndall,PM2.5 Particulates,52.0,ug/m3,"(49.936131, -97.215121)"
32210,15902,2017-09-01 11:34:53,102,Tyndall,PM2.5 Particulates,52.0,ug/m3,"(49.936131, -97.215121)"
32211,15926,2017-09-01 11:39:55,102,Tyndall,PM2.5 Particulates,55.0,ug/m3,"(49.936131, -97.215121)"
32308,15950,2017-09-01 11:44:57,102,Tyndall,PM2.5 Particulates,53.0,ug/m3,"(49.936131, -97.215121)"
32309,15974,2017-09-01 11:49:59,102,Tyndall,PM2.5 Particulates,54.0,ug/m3,"(49.936131, -97.215121)"
32310,15998,2017-09-01 11:55:01,102,Tyndall,PM2.5 Particulates,51.0,ug/m3,"(49.936131, -97.215121)"
32311,16022,2017-09-01 12:00:02,102,Tyndall,PM2.5 Particulates,52.0,ug/m3,"(49.936131, -97.215121)"
32408,16046,2017-09-01 12:05:04,102,Tyndall,PM2.5 Particulates,47.0,ug/m3,"(49.936131, -97.215121)"
32409,16070,2017-09-01 12:10:06,102,Tyndall,PM2.5 Particulates,50.0,ug/m3,"(49.936131, -97.215121)"
32410,16094,2017-09-01 12:15:08,102,Tyndall,PM2.5 Particulates,50.0,ug/m3,"(49.936131, -97.215121)"
32411,16118,2017-09-01 12:20:10,102,Tyndall,PM2.5 Particulates,51.0,ug/m3,"(49.936131, -97.215121)"
32530,16142,2017-09-01 12:25:12,102,Tyndall,PM2.5 Particulates,54.0,ug/m3,"(49.936131, -97.215121)"
32531,16166,2017-09-01 12:30:14,102,Tyndall,PM2.5 Particulates,51.0,ug/m3,"(49.936131, -97.215121)"
32532,16190,2017-09-01 12:35:15,102,Tyndall,PM2.5 Particulates,52.0,ug/m3,"(49.936131, -97.215121)"
32533,16214,2017-09-01 12:40:17,102,Tyndall,PM2.5 Particulates,51.0,ug/m3,"(49.936131, -97.215121)"
32629,16238,2017-09-01 12:45:19,102,Tyndall,PM2.5 Particulates,50.0,ug/m3,"(49.936131, -97.215121)"
32630,16262,2017-09-01 12:50:21,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32631,16286,2017-09-01 12:55:23,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32632,16310,2017-09-01 13:00:24,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32633,16334,2017-09-01 13:05:26,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32730,16358,2017-09-01 13:10:28,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32731,16382,2017-09-01 13:15:29,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32732,16406,2017-09-01 13:20:31,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32733,16430,2017-09-01 13:25:33,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32830,16454,2017-09-01 13:30:34,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32831,16478,2017-09-01 13:35:36,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32832,16502,2017-09-01 13:40:38,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32833,16526,2017-09-01 13:45:40,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32932,16550,2017-09-01 13:50:41,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"
32933,16574,2017-09-01 13:55:43,102,Tyndall,PM2.5 Particulates,48.0,ug/m3,"(49.936131, -97.215121)"

In [26]:
df.groupby('MeasurementType').count()

,ObservationID,ObservationTime,ThingID,LocationName,MeasurementValue,MeasurementUnit,location
MeasurementType,,,,,,,
Humidity,414403,414403,414403,414403,414403,414403,414403
PM2.5 Particulates,414379,414379,414379,414379,414379,414379,414379
Temperature,414386,414386,414386,414386,414386,414386,414386

In [27]:
df.groupby('ThingID')['ObservationID'].nunique()

ThingID
66      90607
72     186065
78     186007
90      47735
96     223724
108    153495
114    130551
120    224984
Name: ObservationID, dtype: int64

In [28]:
table

MeasurementType   Humidity  PM2.5 Particulates  Temperature
ThingID
66               60.550746            9.891129     5.767208
72               65.096568            8.208362    -0.719975
78               64.041758            8.878986    -0.848058
90               61.675058           12.005594    13.758886
96               67.754282           10.434442    -0.182704
108              70.334404            9.018782    -2.200657
114              70.159341            9.807202    -3.888960
120              63.455020            8.455604     0.895021